x-celery-fast: &celery-fast
  build:
    context: .
    dockerfile: ./docker_config/celery/Dockerfile.fast
    args:
      BASE_IMAGE: "${FORCAD_BASE_IMAGE:-forcad_base:local}"

x-service-fast: &service-fast
  build:
    context: .
    dockerfile: ./docker_config/services/Dockerfile.fast
    args:
      BASE_IMAGE: "${FORCAD_BASE_IMAGE:-forcad_base:local}"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker_config/nginx/Dockerfile
      args:
        DNS_RESOLVER: 127.0.0.11

  celery:
    <<: *celery-fast

  flower:
    <<: *celery-fast

  initializer:
    build:
      context: .
      dockerfile: ./docker_config/initializer/Dockerfile.fast
      args:
        BASE_IMAGE: "${FORCAD_BASE_IMAGE:-forcad_base:local}"

  config-loader:
    build:
      context: .
      dockerfile: ./docker_config/initializer/Dockerfile.fast
      args:
        BASE_IMAGE: "${FORCAD_BASE_IMAGE:-forcad_base:local}"

  ticker:
    <<: *service-fast

  client-api:
    <<: *service-fast

  admin-api:
    <<: *service-fast

  events:
    <<: *service-fast

  http-receiver:
    <<: *service-fast
