DROP TABLE IF EXISTS GameConfig CASCADE;
DROP TABLE IF EXISTS GameSession CASCADE;
DROP TABLE IF EXISTS StolenFlags CASCADE;
DROP TABLE IF EXISTS Flags CASCADE;
DROP TABLE IF EXISTS Teams CASCADE;
DROP TABLE IF EXISTS Tasks CASCADE;
DROP TABLE IF EXISTS TeamTasks CASCADE;
DROP TABLE IF EXISTS TeamTasksLog CASCADE;
DROP TABLE IF EXISTS ScheduleHistory CASCADE;
DROP TABLE IF EXISTS CheckerJobs CASCADE;
DROP TABLE IF EXISTS DispatchRuns CASCADE;

DROP FUNCTION IF EXISTS recalculate_rating(INTEGER, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_first_bloods();
DROP FUNCTION IF EXISTS fix_teamtasks();
