export const demoTeams = [
  { name: "danosito's ai farm", logo: "danositos-ai-farm.jpg" },
  { name: "daywave.", logo: "daywave.jpg" },
  { name: "Сборная г. Москва", logo: "moscow.jpg" },
  { name: "W0LV3S_CTF", logo: "w0lv3s-ctf.jpg" },
  { name: "Baba Is Win", logo: "baba-is-win.jpg" },
  { name: "Trippy Troppy", logo: "trippy-troppy.png" },
  { name: "Caplag", logo: "caplag.jpg" },
  { name: "Молоток", logo: "molotok.jpg" },
  { name: "IBEEE", logo: "ibeee.jpg" },
  { name: ".dot", logo: "dot.png" },
  { name: "SEGFAULT", logo: "segfault.png" },
  { name: "мяу мяу", logo: "meow-meow.jpg" },
  { name: "Chetire", logo: "chetire.jpg" },
  { name: "Под Эгидой", logo: "pod-egidoy.png" },
  { name: "CUT", logo: "cut.png" },
  { name: "c4ptur3_Th3_b0br", logo: "c4ptur3-th3-b0br.png" },
  { name: "SIGAN", logo: "sigan.jpg" },
  { name: "NON@me13", logo: "noname13.jpg" },
  { name: "HackTr1ckR0mP", logo: "hacktr1ckr0mp.jpg" },
  { name: "NCF (ex BEST IT)", logo: "ncf.jpg" },
] as const;
