import assert from "node:assert/strict";
import test from "node:test";
import { validateTeam } from "../src/shared/lib/adminValidation.ts";

const team = {
  name: "Team",
  ip: "10.101.0.2",
  token: "0123456789abcdef",
  logo_path: "",
  highlighted: false,
  active: true,
};

test("team token validation matches the server's lowercase hex format", () => {
  assert.equal(validateTeam(team), null);
  for (const token of ["", "abc", "0123456789abcdeF", "0123456789abcde_", "0".repeat(17)]) {
    assert.notEqual(validateTeam({ ...team, token }), null);
  }
});

test("a new team can receive a token generated by the server", () => {
  assert.equal(validateTeam({ ...team, token: "" }, true), null);
});
